export const API_KEY = {
    REVENUE_CAT_IOS: String(process.env.EXPO_PUBLIC_RC_IOS),
    REVENUE_CAT_ANDROID: String(process.env.EXPO_PUBLIC_RC_ANDROID),
    MAPBOX_ACCESS_TOKEN: String(process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN),
    TOMTOM: String(process.env.EXPO_PUBLIC_TOMTOM_API_KEY),
    TANKERKOENIG: String(process.env.EXPO_PUBLIC_TANKERKOENIG_API_KEY),
    GEOAPIFY: String(process.env.EXPO_PUBLIC_GEOAPIFY_API_KEY),
};

export const REFETCH_INTERVAL = {
    ARRIVAL_TIME_IN_SECONDS: Number(process.env.EXPO_PUBLIC_ARRIVAL_TIME_REFETCH_INTERVAL_SECONDS) * 1000,
    INCIDENTS_IN_MINUTES: Number(process.env.EXPO_PUBLIC_INCIDENTS_REFETCH_INTERVAL) * 1000 * 60,
    GAS_STATIONS_IN_MINUTES: Number(process.env.EXPO_PUBLIC_GAS_STATIONS_REFETCH_INTERVAL_MINUNTES) * 1000 * 60,
    SPEED_CAMERAS_IN_MINUTES: Number(process.env.EXPO_PUBLIC_SPEED_CAMERAS_REFETCH_INTERVAL) * 1000 * 60,
};

export const THRESHOLD = {
    NAVIGATION: {
        ROUTE_DEVIATION_METERS: Number(process.env.EXPO_PUBLIC_ROUTE_DEVIATION_THRESHOLD_IN_METERS),
        NEXT_STEP_IN_METERS: Number(process.env.EXPO_PUBLIC_NEXT_STEP_THRESHOLD_IN_METERS),
        IS_ON_SAME_LANE_IN_DEGREES: Number(process.env.EXPO_PUBLIC_IS_ON_SAME_LANE_THRESHOLD_IN_DEGREES),
        IS_AHEAD_IN_DEGREES: Number(process.env.EXPO_PUBLIC_IS_AHEAD_THRESHOLD_IN_DEGREES),
        ROUTE_BUFFER_TOLERANCE: Number(process.env.EXPO_PUBLIC_ROUTE_BUFFER_TOLERANCE_IN_METERS),
    },

    INCIDENT: {
        SHOW_IN_METERS: Number(process.env.EXPO_PUBLIC_SHOW_INCIDENTS_THRESHOLD_IN_METERS),
        WARNING_IN_METERS: Number(process.env.EXPO_PUBLIC_WARNING_INCIDENT_THRESHOLD_IN_METERS),
    },

    SPEED_CAMERA: {
        SHOW_IN_METERS: Number(process.env.EXPO_PUBLIC_SHOW_SPEED_CAMERAS_THRESHOLD_IN_METERS),
        WARNING_IN_METERS: Number(process.env.EXPO_PUBLIC_WARNING_SPEED_CAMERA_THRESHOLD_IN_METERS),
    },

    GAS_STATION: {
        SHOW_IN_KILOMETERS: Number(process.env.EXPO_PUBLIC_SHOW_GAS_STATIONS_THRESHOLD_IN_KILOMETERS),
        PRICE_DIFFERENCE_IN_PERCENT: Number(process.env.EXPO_PUBLIC_GAS_STATION_PRICE_DIFFERENCE_THRESHOLD_IN_PERCENT),
    },

    SPEED_LIMIT: {
        SHOW_IN_METERS: Number(process.env.EXPO_PUBLIC_SHOW_SPEED_LIMIT_THRESHOLD_IN_METERS),
    },
};
