export const API = {
    REVENUE_CAT_IOS: String(process.env.EXPO_PUBLIC_RC_IOS),
    REVENUE_CAT_ANDROID: String(process.env.EXPO_PUBLIC_RC_ANDROID),
    UWAY_URL: String(process.env.EXPO_PUBLIC_UWAY_API_URL),
    UWAY_WS_URL: String(process.env.EXPO_PUBLIC_UWAY_WS_URL),
    MAPBOX_ACCESS_TOKEN: String(process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN),
};

export const REFETCH_INTERVAL = {
    ARRIVAL_TIME_IN_SECONDS: Number(process.env.EXPO_PUBLIC_ARRIVAL_TIME_REFETCH_INTERVAL_SECONDS) * 1000,
    INCIDENTS_IN_MINUTES: Number(process.env.EXPO_PUBLIC_INCIDENTS_REFETCH_INTERVAL) * 1000 * 60,
    GAS_STATIONS_IN_MINUTES: Number(process.env.EXPO_PUBLIC_GAS_STATIONS_REFETCH_INTERVAL_MINUNTES) * 1000 * 60,
    SPEED_CAMERAS_IN_MINUTES: Number(process.env.EXPO_PUBLIC_SPEED_CAMERAS_REFETCH_INTERVAL) * 1000 * 60,
    AUTH_TOKEN_IN_HOURS: Number(process.env.EXPO_PUBLIC_AUTH_TOKEN_REFETCH_INTERVAL_HOURS) * 1000 * 60 * 60,
    SPEED_LIMITS_IN_SECONDS: Number(process.env.EXPO_PUBLIC_SPEED_LIMITS_REFETCH_INTERVAL) * 1000,
};

export const THRESHOLD = {
    NAVIGATION: {
        ROUTE_DEVIATION_METERS: Number(process.env.EXPO_PUBLIC_ROUTE_DEVIATION_THRESHOLD_IN_METERS),
        DISTANCE_IN_METERS: Number(process.env.EXPO_PUBLIC_DISTANCE_THRESHOLD_IN_METERS),
        SNAP_RADIUS_IN_METERS: Number(process.env.EXPO_PUBLIC_SNAP_RADIUS_IN_METERS),
        MIN_ACCURACY: Number(process.env.EXPO_PUBLIC_MIN_ACCURACY),
        GPS_WARNING_THRESHOLD: Number(process.env.EXPO_PUBLIC_GPS_WARNING_THRESHOLD),
        SPEECH_COOLDOWN_IN_SECONDS: Number(process.env.EXPO_PUBLIC_SPEECH_COOLDOWN_IN_SECONDS) * 1000,
        UTURN_ANGLE_MIN: Number(process.env.EXPO_PUBLIC_UTURN_ANGLE_MIN),
        UTURN_ANGLE_MAX: Number(process.env.EXPO_PUBLIC_UTURN_ANGLE_MAX),
        MAX_SNAP_HEADING_DIFFERENCE: Number(process.env.EXPO_PUBLIC_MAX_SNAP_HEADING_DIFFERENCE),
    },

    SPEED_LIMIT: {
        SHOW_IN_METERS: Number(process.env.EXPO_PUBLIC_SHOW_SPEED_LIMIT_THRESHOLD_IN_METERS),
    },
};
